// app
export const MAILING_LIST_SUCCESS = 'MAILING_LIST_SUCCESS'

// current_member
export const UPDATE_CURRENT_MEMBER = 'UPDATE_CURRENT_MEMBER'

// next_event
export const UPDATE_NEXT_EVENT = 'UPDATE_NEXT_EVENT'

// sign_in_stage
export const UPDATE_SIGN_IN_STAGE = 'UPDATE_SIGN_IN_STAGE'

// can comment out everything above

export const actions = {
   MAILING_LIST_SUCCESS: 'MAILING_LIST_SUCCESS',
   UPDATE_CURRENT_MEMBER: 'UPDATE_CURRENT_MEMBER',
   UPDATE_CURRENT_MEMBER_AGE: 'UPDATE_CURRENT_MEMBER_AGE',
   UPDATE_NEXT_EVENT: 'UPDATE_NEXT_EVENT',
   UPDATE_SIGN_IN_STAGE: 'UPDATE_SIGN_IN_STAGE',
}
